#common
#log_home: '/application/search/python/offprice/myapp.log'
#sqlite3_data: '/application/search/python/offprice/data.db'
log_home: 'D:/temp/myapp.log'
sqlite3_data: 'D:/temp/data.db'
keyword: 

#e-mail
mail_sender: ****
mail_subject: '最新促销信息'
mail_smtpserver: 'smtp.163.com'
mail_username: '****'
mail_password: '***'
mail_to: '***'

#sina_weibo
sina_accesstoken: '**'

#yiqifa
yiqifa_appkey: **
yiqifa_secret: **
yiqifa_url: 'openapi.yiqifa.com'

#smzdm
smzdm_url: 'http://feed.smzdm.com/'

#smzdt
smzdt_url: 'http://feed.feedsky.com/smzdt'

